export const ActionTypes = {
    SET_SELECTED_CATAGORY: "SET_SELECTED_CATAGORY",
    REMOVE_SELECTED_CATAGORY: "REMOVE_SELECTED_CATAGORY",
    BUYING_OR_SELLING: "BUYING_OR_SELLING",
    SET_SEARCH: "SET_SEARCH",
    SET_VEHICLE_PAGE1: "SET_VEHICLE_PAGE1",
    SET_VEHICLE_PAGE2: "SET_VEHICLE_PAGE2",
    SET_VEHICLE_PAGE3: "SET_VEHICLE_PAGE3",
    SET_VEHICLE_PAGE4: "SET_VEHICLE_PAGE4",
    SET_VEHICLE_PAGE5: "SET_VEHICLE_PAGE5",
    SET_CHOOSE_PLAN: "SET_CHOOSE_PLAN",

    SET_REALSTATE_PAGE1: " SET_REALSTATE_PAGE1",
    SET_REALSTATE_PAGE2: " SET_REALSTATE_PAGE2",
    SET_REALSTATE_PAGE3: " SET_REALSTATE_PAGE3",
    SET_REALSTATE_PAGE4: " SET_REALSTATE_PAGE4",
    SET_REALSTATE_PAGE5: " SET_REALSTATE_PAGE5",
    SET_REALSTATE_PAGE6: " SET_REALSTATE_PAGE6",

    SET_BUSINESS_PAGE1: " SET_BUSINESS_PAGE1",
    SET_BUSINESS_PAGE2: " SET_BUSINESS_PAGE2",

    SET_FASHION_PAGE1: " SET_FASHION_PAGE1",
    SET_FASHION_PAGE2: " SET_FASHION_PAGE2",
    SET_FASHION_PAGE3: " SET_FASHION_PAGE3",

    SET_SECONDHAND_PAGE1: " SET_SECONDHAND_PAGE1",
    SET_SECONDHAND_PAGE2: " SET_SECONDHAND_PAGE2",
    SET_SECONDHAND_PAGE3: " SET_SECONDHAND_PAGE3",

    SET_PETS_PAGE1: " SET_PETS_PAGE1",
    SET_PETS_PAGE2: " SET_PETS_PAGE2",
    SET_PETS_PAGE3: " SET_PETS_PAGE3",

    SET_VIEW_ITEM: " SET_VIEW_ITEM",

    SET_SHPPING_PAGE1: " SET_SHPPING_PAGE1",
    SET_SHPPING_PAGE2: " SET_SHPPING_PAGE2",
}